apiVersion: v1
kind: Service
metadata:
  name: agent-cockpit
  labels:
    app: agent-cockpit
spec:
  type: ClusterIP
  selector:
    app: agent-cockpit
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
